### ISSUE TITLE
ESP32-S3-Box3: Utilize Sensor-DOCK 

### ISSUE THREAD

**Issue by ChristophCaina** [esphome/firmware#133]
The ESP32-S3-Box3 comes with a collection of different stands.

![image](https://github.com/esphome/firmware/assets/26391061/87ebddd8-8da9-4369-89ce-27a0eefefe66)

The "default" DOCK does not have much options to support, but the SENSOR does come with an AHT30 Temperature Sensor, a RADAR Sensor, an IR Receiver and Transmitter - and some other options, such as an SD-Card Reader...

It would be great, if the Firmware could provide some options to utilize the Sensors from the SENSOR dock...
I know, that most are not yet available within ESPHome (the RadarSensor, for Example), But the AHT30 could be used with the AHT20 variant of AHT10 component ...

[EDIT]

With adding the following to the config, the AHT30 can already be used:

```
i2c:
  - id: bus_a
    sda: GPIO08
    scl: GPIO18
    scan: true

  - sda: GPIO41
    scl: GPIO40
    id: bus_b

sensor:
  - platform: aht10
    variant: AHT20
    i2c_id: bus_b
    temperature:
      name: ${name_temperature}
    humidity:
      name: ${name_humidity}
    update_interval: 60s
```
