### ISSUE TITLE
Feature: Continued conversation with text on screen for ESP32-S3-Box-3

### ISSUE THREAD

**Issue by jaymunro** [esphome/firmware#174]
This is in draft PR #173 pending more testing.

Here is a demo video of this beta of Voice assistant with Continued conversation and text.

[![IMG_1020](https://github.com/esphome/firmware/assets/1166024/c1ac51d8-1eea-4d51-8837-55c537586033)
Demo of Continued conversation BETA](https://drive.google.com/file/d/1DjV5XPmsqwHq7iph_kFEb6XFILpzw4Pt/view)

I'm looking for testers who can give feedback on issues, further suggestions for improvement, etc. I've tested it with the HA streaming wake word but it works much better with the on-device wake word. Once it is verified, we can hopefully get it accepted in the ESPHome repository for everybody. Please leave issues and suggestions here.

To install, in your device's yaml change this:
```
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml
  ...
```
to this:
```
packages:
  # esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml
  esphome.voice-assistant: github://jaymunro/esphome_firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@continued-conversation
  ...
```

If you change the wake word model, add another substitution for the wake word text as follows:
```
substitutions:
  ...
  micro_wake_word_model: hey_jarvis
  wake_word_text: "Hey Jarvis"
```

Note this is a beta and the repo above is temporary until after [the PR](https://github.com/esphome/firmware/pull/173) is accepted.

Before doing an **Install**, be sure to do a **Clean build files** from the 3-dot hamburger menu in ESPHome.

**Comment by jaymunro** [comment]
Comments in https://community.home-assistant.io/t/esp32-s3-box3/638287/289 so far confirm operation and request the following:
> The display text is working pretty good - except localization (it’s in EN) - is there any chance to get it working in system default language (mine is Slovenian for example)?

> Wake word: from time to time the I get in the log:
> `09:31:48][D][voice_assistant:349]: Speaker buffer full, trying again next loop`

> the text doesn’t support some char, I’m french and turn off is “Éteins” It show a black rectangle instead of the É. would it be possible to have change the format of the date ? and time ?

> ...but in fact I need just: ščž ŠČŽ. As for date and time: "%d.%m.%y"

> I would vote for a 24-hour clock (no AM/PM). And I would like the Danish letters æ ø å Æ Ø Å to be included

> you can dynamically change the pipeline and so the wake word when not using the in device, that’s why the text can’t be good, or we could have a text_sensor to change it (I would love that in fact)

> latin like french and spanish would need :
> é É ç Ç è È ê Ê à À ô
> there is more but not sure if we need them maybe we should find a way to have all of them, don’t know about the correct way to do that

**Comment by jaymunro** [comment]
I have now modified the glyphs to add Slovenian, Danish, French, Spanish, German
```
    glyphs:
      '&@!"''%()+=,-_.:°/?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzščžŠČŽæøåÆØÅéÉçÇèÈêÊàÀôäüöÄÜÖß'
```

**Comment by pepe59** [comment]
It could also be added for Czech.
Thank you

glyphs: ' !"%()+,-.:/0123456789AÁBCČDĎEÉĚFGHIÍJKLMNOÓPQRŘSŠTŤUÚVWXYZŽ_abcdefghijklmnopqrstuvwxyzěščřžýáíéťúů°'

**Comment by Bluhme1** [comment]
Would like to have an option to shift to 24-hour clock as we use in Continental Europe

Danish characters work beautifully 

/Lars

**Comment by jaymunro** [comment]
I have found this link https://www.underware.nl/latin_plus/character_set/
Hopefully that will cover all needs without needing too many resources from the Box3.

I have in testing a version with 'date format' and 'time format' dropdown menus to replace the single dropdown presently in use and hope to put this up later today.

**Comment by jaymunro** [comment]
New version is up with many many more glyphs, fix for stuck condition at boot, and methods for selecting date and/or time formats.

Next is methods to allow for different languages in the text prompts.

**Comment by jaymunro** [comment]
Method has now been added for multilingual text. Reinstall the same package and see https://github.com/esphome/firmware/pull/173#issuecomment-1980124041 on how to use.

**Comment by bobzer** [comment]
Thanks for the new format, it's great, I would love to get a few more format without year, like 5th march and tuesday 5th march.
My current config is :

```
substitutions:
  name: "esp32-s3-box-3"
  friendly_name: S3 Box 3
  starting_up: "Démarrage..."
  wake_word_prompt: "Dis \\\"Okay Nabu\\\""
  listening_prompt: "Que puis-je faire ?"
  error_prompt: "Oups, Désolé"

packages:
  # esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
  esphome.voice-assistant: github://jaymunro/esphome_firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@continued-conversation
  esphome.voice-assistant-sensor: github://jaymunro/esphome_firmware/esp32-box-docks/box3-sensor-for-voice-assistant.yaml@sensor_dock

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: *****************

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

but the text is still in english
