### ISSUE TITLE
Can't update S3 Box because of duplicate OTA instance

### ISSUE THREAD

**Issue by TheZoker** [esphome/firmware#216]
Hi there,

This is my yaml config:
```yaml
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box.yaml@main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ESPHome Fallback"
    password: !secret api_password

ota:
  - platform: esphome
    password: !secret api_password
```

Every time I try to compile this, I get this error:
```
Failed config

ota.esphome: [source /data/packages/c46f54c1/wake-word-voice-assistant/esp32-s3-box.yaml:85]
  
  Only one instance of the esphome ota platform is allowed per port. Note that this error may result from OTA specified in packages.
  platform: esphome
  id: ota_esphome
  version: 2
  port: 3232
```

Since all my devices use a password for OTA I'm not sure how to solve this. Can somebody help me fix this? Thanks!
