### ISSUE TITLE
VoiceAssist 2024.8.1 update issues

### ISSUE THREAD

**Issue by ChristophCaina** [esphome/firmware#251]
Hi,
HomeAssistant is showing Updates for my S3-Box and S3-Box3 for Version 2024.8.1...
But something seems not to be right with it...

maybe, this is somehow a messed up installation of my ESP boxes... but as soon as I update, HomeAssist will auto-detect a new instance of the Improv - and when I try to configure it, it will fail.

Also, both ESPBoxes have now two "Firmware Version" entities available...one showing an available update, the other one "up-to-date"
![image](https://github.com/user-attachments/assets/6faa08ef-3755-4a5d-bc3b-377cc7ff1ccf)

![image](https://github.com/user-attachments/assets/5c4f7003-b786-49e3-ac4f-ba3d85909f19)
![image](https://github.com/user-attachments/assets/fd2d72d3-34d6-4313-a8b6-29f1523de65d)

The ESPHomeDashboard itself does not show that any update is available:
![image](https://github.com/user-attachments/assets/97ceac16-c9fc-4994-b7e5-5770f4f233d9)

The source of my two boxes:

S3-Box
```
substitutions:
  name: esp32-s3-box-d4ff80
  friendly_name: ESP32 S3 Box Voice Assist

  loading_illustration_file: android/loading.png
  idle_illustration_file: android/sleeping.png
  listening_illustration_file: android/happy.png
  thinking_illustration_file: android/thinking.png
  replying_illustration_file: android/happy2.png
  error_illustration_file: android/sad_tear.png

  loading_illustration_background_color: 'ffffff'
  idle_illustration_background_color: 'ffffff'
  listening_illustration_background_color: 'ffffff'
  thinking_illustration_background_color: 'ffffff'
  replying_illustration_background_color: 'ffffff'
  error_illustration_background_color: 'ffffff'

packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: **********

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

micro_wake_word:
  models:
    - model: github://esphome/micro-wake-word-models/models/v2/okay_nabu.json
    - model: github://esphome/micro-wake-word-models/models/v2/hey_jarvis.json
```

S3-Box3
```
substitutions:
  name: esp32-s3-box-3-5acd3c
  friendly_name: ESP32 S3 Box3 Voice Assist

  loading_illustration_file: android/loading.png
  idle_illustration_file: android/sleeping.png
  listening_illustration_file: android/happy.png
  thinking_illustration_file: android/thinking.png
  replying_illustration_file: android/happy2.png
  error_illustration_file: android/sad_tear.png

  loading_illustration_background_color: 'ffffff'
  idle_illustration_background_color: 'ffffff'
  listening_illustration_background_color: 'ffffff'
  thinking_illustration_background_color: 'ffffff'
  replying_illustration_background_color: 'ffffff'
  error_illustration_background_color: 'ffffff'

packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
  
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: **********

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

micro_wake_word:
  models:
    - model: github://esphome/micro-wake-word-models/models/v2/okay_nabu.json
    - model: github://esphome/micro-wake-word-models/models/v2/hey_jarvis.json

i2c:
  - id: bus_a
    sda: GPIO08
    scl: GPIO18
    scan: false
    sda_pullup_enabled: true
    scl_pullup_enabled: true
    frequency: 100kHz

  - sda: GPIO41
    scl: GPIO40
    scan: false
    sda_pullup_enabled: true
    scl_pullup_enabled: true
    frequency: 50kHz
    id: bus_b

at581x:
  id: "Radar"
  i2c_id: bus_a

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
    name: "Presence detect"
    disabled_by_default: false
    device_class: "occupancy"

switch:
  - platform: template
    name: "Mute when absent"
    id: mute_when_absent
    icon: mdi:account-right-arrow
    optimistic: true
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: at581x
    at581x_id: "Radar"
    name: "Enable Radar"

number:
  - platform: template
    name: "Presence duration"
    id: radar_delayed_off
    icon: mdi:account-clock
    optimistic: true
    restore_value: true
    initial_value: 60
    min_value: 0
    step: 5
    max_value: 300
    unit_of_measurement: s
    entity_category: config
    mode: box
```

Also, what I don't understand:
The S3-Box does have some entities, which are not available in the wake-word-voice-assistant source, such as "Safe Mode Boot" - which should only be available for the "Voice-Assistant" firmware

![image](https://github.com/user-attachments/assets/c506fdf8-3da5-424c-9069-58b19722fae4)
