### ISSUE TITLE
Wake word cannot be enabled

### ISSUE THREAD

**Issue by MStankiewiczOfficial** [esphome/firmware#294]
After installing the software available at [ESPHome](https://esphome.io/projects/), wake work does not work. Configuration options for the wake word are unavailable. Updating to the latest version (2024.12.4) did not help.

**Device**: M5Stack Atom Echo

**Configuration**:
```
substitutions:
  name: m5stack-atom-echo-311e5c
  friendly_name: M5Stack Atom Echo 311e5c

packages:
  m5stack.atom-echo: github://esphome/media-players/m5stack/m5stack-atom-echo.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: [CENSORED]


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
