### ISSUE TITLE
S3 Box ... Does the Display work?

### ISSUE THREAD

**Issue by ChristophCaina** [esphome/firmware#62]
Hi,
until now, I've just used my S3Box as a Bluetooth Proxy which was showing the current Time and Date on its Display.
Now, I am trying to implement the WakeWord configuration you've provided here (https://github.com/esphome/firmware/blob/main/voice-assistant/esp32-s3-box.yaml) and wonder, if this is not working with the Display Configuration...

here's my old config:

```
i2c:
  scl: GPIO18
  sda: GPIO8
  scan: true

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

# The Display itself and what's visible on it...
display:
  - platform: ili9xxx
    model: S3BOX
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin: GPIO48
    id: lcd
    lambda: |-
      it.fill(Color(255, 255, 255));
      it.strftime(160, 85, id(font_time), Color::BLACK, TextAlign::CENTER, "%H:%M:%S", id(time_ha).now());
      it.strftime(160, 170, id(font_date), Color::BLACK, TextAlign::CENTER, "%d.%m.%Y", id(time_ha).now());

# Which Fonts we want to use
font:
  - file: "gfonts://Roboto"
    id: font_time
    size: 60
    glyphs: "0123456789:"
  - file: "gfonts://Roboto"
    id: font_date
    size: 50
    glyphs: "0123456789."
  - file: "gfonts://Roboto"
    id: font_small
    size: 20

# get the Time from Home-Assistant
time:
  - platform: homeassistant
    id: time_ha
    timezone: Europe/Berlin
```
