### ISSUE TITLE
Wake Word and PTT - Best of both worlds

### ISSUE THREAD

**Issue by timmo001** [esphome/firmware#75]
Is there a way to be able to use the push to talk whilst wake word is enabled? I've been experimenting but couldnt find a way other than disabling wake word and turning it back on after a 30 seconds or so

```
      - if:
          condition:
            switch.is_off: use_wake_word
          then:
            - if:
                condition: voice_assistant.is_running
                then:
                  - voice_assistant.stop:
                  - delay: 1s
                  - script.execute: reset_led
                  - script.wait: reset_led
            - voice_assistant.start:
          else:
            - voice_assistant.stop:
            - switch.turn_off: use_wake_word
            - delay: 1s
            - voice_assistant.start:
            - delay: 30s
            - switch.turn_on: use_wake_word

```
